# Configuration file for MegaLinter
# See all available variables at https://megalinter.github.io/configuration/ and in linters documentation

APPLY_FIXES: none # all, none, or list of linter keys
# ENABLE: # If you use ENABLE variable, all other languages/formats/tooling-formats will be disabled by default
PRE_COMMANDS:
  - command: npm install eslint-config-next@12.1.6 stylelint-config-styled-components@0.1.1 stylelint-config-yandex-plus-order @stylelint/postcss-css-in-js@0.38.0 postcss-syntax@0.36.2
    cwd: "root"        # Will be run at the root of MegaLinter docker image
ENABLE_LINTERS:
  - JAVASCRIPT_ES
  - JSX_ESLINT
  - JAVASCRIPT_PRETTIER
  - TYPESCRIPT_ES
  - TSX_ESLINT
  - TYPESCRIPT_PRETTIER
  # - CSS_STYLELINT
DISABLE:
  - COPYPASTE # Comment to enable checks of excessive copy-pastes
  - SPELL # Comment to enable checks of spelling mistakes
SHOW_ELAPSED_TIME: false
FILEIO_REPORTER: false
JAVASCRIPT_DEFAULT_STYLE: prettier
TYPESCRIPT_DEFAULT_STYLE: prettier
TYPESCRIPT_PRETTIER_FILE_EXTENSIONS: [".ts", ".tsx"]
# CSS_STYLELINT_FILE_EXTENSIONS: [".js", ".ts", ".tsx"]
# DISABLE_ERRORS: true # Uncomment if you want MegaLinter to detect errors but not block CI to pass
