name: Code Checks

on:
  push:
    branches: [ "master" ]

jobs:
  eslint:
    name: runner / eslint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 14
          cache: 'yarn'
      - run: yarn install --frozen-lockfile
      - uses: reviewdog/action-eslint@v1
        with:
          reporter: github-check
          fail_on_error: true

  stylelint:
    name: runner / stylelint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 14
          cache: 'yarn'
      - run: yarn install --frozen-lockfile
      - uses: reviewdog/action-stylelint@v1
        with:
          reporter: github-check
          stylelint_input: '**/*.{js,jsx,ts,tsx}'
          fail_on_error: true

  tsc:
    name: runner / tsc
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 14
          cache: 'yarn'
      - run: yarn install --frozen-lockfile
      - uses: EPMatt/reviewdog-action-tsc@v1
        with:
          reporter: github-check
          fail_on_error: true